// cerebro.js - BÚNKER 2: IDIOMA FIJO Y SEO ESTRATÉGICO

const PROMPTS = {
  INTRO: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### I. INTRODUCCIÓN Y RESUMEN DEL ACTIVO\nExplica con prosa de consultor de élite quiénes somos (PredictaCore) y nuestro enfoque. Redacta un diagnóstico agudo del activo analizado usando de 3 a 5 líneas fluidas por idea, y declara explícitamente su PAÍS/MERCADO OBJETIVO. Dossier: ${d}`,

  GEMELOS: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### II. PERFILES PSICOLÓGICOS\nDiseña 4 perfiles de Gemelos Sintéticos. Redacta de 3 a 5 líneas fluidas por perfil, profundizando en sus dolores y motivaciones de compra. Dossier: ${d}`,

  SCORECARD: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### III. SCORECARD DE SALUD COMERCIAL\nPresenta una tabla Markdown ESTRICTAMENTE con esta cabecera exacta:\n| Punto de Salud | Calificación (1-10) | Diagnóstico Forense |\n|---|---|---|\nREGLAS INQUEBRANTABLES:\n1. Genera EXACTAMENTE 10 filas de evaluación completas.\n2. PROHIBIDO usar saltos de línea (Enter) dentro de las celdas. Todo el texto de una celda debe ir en una sola línea continua.\n3. En el Diagnóstico Forense, usa de 3 a 5 líneas de profundidad analítica. Dossier: ${d}`,

  VISIBILIDAD: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### IV. VISIBILIDAD EXTERNA\nEres un consultor de Élite. Analiza la situación de visibilidad orgánica del negocio basándote en la información del dossier. Escribe con esta estructura exacta (sin títulos principales adicionales):\n1. **Fricción de Autoridad y Confianza**: Analiza cómo la reputación actual (reseñas positivas vs. quejas críticas) afecta la capacidad del dominio para convertir tráfico orgánico (3 a 5 líneas).\n2. **Vulnerabilidad por Dependencia**: Evalúa el riesgo financiero y estratégico de depender de plataformas de terceros (como Etsy u otros marketplaces) frente a la necesidad de construir autoridad en el dominio propio (3 a 5 líneas).\n3. **Brechas de Búsqueda Transaccional**: Nombra 3 palabras clave o "Long-Tail Keywords" EN ESPAÑOL altamente transaccionales que este negocio DEBE dominar orgánicamente.\n4. **Ejes de Contenido Estratégico**: Propón 2 temáticas de contenido (ej. guías de compra, comparativas de materiales) que el negocio debería desarrollar para capturar tráfico de alta intención y posicionarse como autoridad en su nicho (3 a 5 líneas). Dossier: ${d}`,

  BENCHMARK: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### V. RADIOGRAFÍA ESTRATÉGICA (BENCHMARK)\nElige a 3 competidores reales del nicho. Presenta una tabla Markdown ESTRICTAMENTE con esta estructura (Reemplaza "Comp 1", etc., por sus NOMBRES REALES):\n| Criterio de Análisis | Activo Analizado | [Nombre Comp 1] | [Nombre Comp 2] | [Nombre Comp 3] |\n|---|---|---|---|---|\nREGLAS INQUEBRANTABLES:\n1. PROHIBIDO usar saltos de línea (Enter) dentro de las celdas.\n2. Evalúa 3 puntos de fricción profundos. Redacta de 3 a 5 líneas fluidas (sin dar Enter) por celda. Dossier: ${d}`,

  SWOT: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### VI. MATRIZ ESTRATÉGICA\nDesarrolla el análisis en Fortalezas, Debilidades, Oportunidades y Amenazas. Redacta de 3 a 5 líneas por punto. REGLA INQUEBRANTABLE: Inicia CADA viñeta con un número y un punto (ejemplo: 1., 2., 3., 4.). Dossier: ${d}`,

  WISHLIST: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### VII. LISTA DE DESEOS\nDesarrolla 10 características tácticas de alto valor (3 a 5 líneas por punto). REGLA INQUEBRANTABLE: Inicia cada punto estrictamente con un NÚMERO y un PUNTO (1., 2., 3. hasta el 10.). NO uses guiones. Dossier: ${d}`,

  FUGAS: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### VIII. 15 PUNTOS DE FUGA\nIdentifica 15 hallazgos críticos de fricción. Marca las más destructivas como **[HEMORRAGIA CRÍTICA]**. REGLA INQUEBRANTABLE: Inicia cada punto estrictamente con un NÚMERO y un PUNTO (1., 2., 3. hasta el 15.). Para las Hemorragias Críticas, DEBES profundizar de 3 a 5 líneas explicando el problema exacto y su impacto financiero letal. Dossier: ${d}`,

  ACCIONES: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### IX. 15 ACCIONES TÁCTICAS\nProporciona la solución exacta para sellar las 15 fugas. Explica la solución de forma clara y accionable usando de 3 a 5 líneas por punto. REGLA INQUEBRANTABLE: Inicia cada punto estrictamente con un NÚMERO y un PUNTO (1., 2., 3. hasta el 15.). Dossier: ${d}`,

  HERRAMIENTAS: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### X. HERRAMIENTAS DE ESCALA\nRecomienda EXACTAMENTE 5 soluciones SaaS específicas (3 a 5 líneas justificando el ROI de cada una). REGLA INQUEBRANTABLE: Inicia cada punto con un NÚMERO y un PUNTO (1., 2., 3., 4., 5.). Dossier: ${d}`,

  OMNI: (d) => `REGLA ESTRICTA: Redacta toda tu respuesta EN ESPAÑOL.\nInicia tu respuesta EXACTAMENTE con este encabezado: ### XI. HOJA DE RUTA EJECUTIVA (21 DÍAS)\nDesarrolla un cronograma dividido en 3 fases de 7 días. REGLA INQUEBRANTABLE: Inicia cada paso de cada fase con un NÚMERO y un PUNTO (1., 2., 3.). Explica la ejecución táctica de cada paso usando de 3 a 5 líneas. Dossier: ${d}`
};

module.exports = { PROMPTS };
