// cerebro.js - BÚNKER 2: MULTILINGÜE ESTRICTO, SEO TRADUCIDO Y LISTAS BLINDADAS
const IDIOMA = "INSTRUCCIÓN CRÍTICA Y ABSOLUTA: Detecta el idioma principal del sitio web analizado (basado en el Dossier y las Imágenes). DEBES redactar tu respuesta COMPLETA (incluyendo el encabezado, el análisis, las tablas y las viñetas) ESTRICTAMENTE en ese idioma detectado. Cero mezclas.";
const REGLA_NUCLEAR = "REGLA NUCLEAR DE AUDITORÍA: TIENES ESTRICTAMENTE PROHIBIDO mencionar reseñas de clientes, testimonios, o quejas (como manchas o defectos) en NINGUNA PARTE del reporte, CON EXCEPCIÓN ÚNICA de la Sección IV (Visibilidad y SEO).";
const FORMATO_LISTAS = "INSTRUCCIÓN DE FORMATO FATAL: TIENES ESTRICTAMENTE PROHIBIDO usar viñetas simples (bullets como • o -). DEBES iniciar cada punto OBLIGATORIAMENTE con un NÚMERO seguido de un PUNTO y un ESPACIO. Ejemplo CORRECTO: '1. [Texto]'. Ejemplo INCORRECTO: '• [Texto]'.";

const PROMPTS = {
  INTRO: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### I. INTRODUCCIÓN Y RADIOGRAFÍA DEL ACTIVO\nRedacta esta sección estructurada estrictamente en dos partes:\nPÁRRAFO 1 (Nuestra Identidad): Explica con autoridad, agresividad y un tono de élite quiénes somos (PredictaCore). DEBES mencionar que simulamos más de 9,000 interacciones de fricción. PÁRRAFO 2 (El Negocio): Describe profundamente el activo analizado basado en el Dossier. ¿Qué venden? ¿A quién? ¿Cuál es su modelo? Dossier: ${d}`,
  GEMELOS: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### II. GEMELOS SINTÉTICOS Y PSICOLOGÍA DE COMPRA\nDefine 4 perfiles mentales (Buyer Personas) que visitan este sitio. Para cada uno indica: 1. Perfil. 2. Motivación. 3. Barrera de compra (basada en el dossier). Dossier: ${d}`,
  SCORECARD: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### III. SCORECARD DE SALUD COMERCIAL\nCrea una tabla con 10 pilares (UX, Confianza, Oferta, Cierre, etc.). Califica de 1 a 10 y justifica brevemente. Dossier: ${d}`,
  VISIBILIDAD: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### IV. VISIBILIDAD Y AUTORIDAD DE MERCADO\nAnaliza el SEO y la autoridad. Aquí SÍ puedes mencionar qué dice la gente o cómo se ve el sitio en el mercado. Dossier: ${d}`,
  BENCHMARK: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### V. BENCHMARK COMPETITIVO\nCrea una tabla comparativa con 3 competidores reales del nicho detectado. Dossier: ${d}`,
  SWOT: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### VI. MATRIZ FODA TÁCTICA\nAnaliza Fortalezas, Oportunidades, Debilidades y Amenazas. Dossier: ${d}`,
  WISHLIST: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### VII. LISTA DE DESEOS\n10 características tácticas de alto valor (3 a 5 líneas). ${FORMATO_LISTAS} (Numera del 1 al 10). Dossier: ${d}`,
  FUGAS: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### VIII. 15 PUNTOS DE FUGA\nIdentifica 15 hallazgos críticos de fricción. Marca las peores como **[HEMORRAGIA CRÍTICA]**. REGLAS: 1. ${FORMATO_LISTAS} (Numera del 1 al 15). 2. Evalúa ERRORES MICRO (botones, usabilidad, contraste, carga). Dossier: ${d}`,
  ACCIONES: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### IX. 15 ACCIONES TÁCTICAS\nProporciona la solución exacta a las 15 fugas. REGLA: ${FORMATO_LISTAS} (Numera del 1 al 15). Incluye acciones claras de rediseño UX/UI. Dossier: ${d}`,
  HERRAMIENTAS: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### X. HERRAMIENTAS DE ESCALA\n5 soluciones SaaS (3 a 5 líneas cada una). Dossier: ${d}`,
  OMNI: (d) => `${IDIOMA}\n${REGLA_NUCLEAR}\nEscribe este encabezado traducido al idioma detectado: ### XI. HOJA DE RUTA OMNICANAL (21 DÍAS)\nDivide en 3 fases de 7 días cada una. Explica qué hacer día por día para corregir el activo. Dossier: ${d}`
};

module.exports = { PROMPTS, IDIOMA, REGLA_NUCLEAR };
