[phases.setup]
nixPkgs = ['nodejs_18', 'chromium', 'nss', 'atk', 'cups', 'libdrm', 'libxkbcommon', 'pango', 'cairo', 'libgbm', 'libasound2']

[phases.build]
cmds = ["npm install", "npx playwright install-deps chromium"]

[start]
cmd = "npm start"
